Repository samundra/whoowesme, pull requests merged in 2020-10, with the labels that each got.

#202 Initiate backend in nestjs
  api/README.md
  api/src/core/MyLogger.ts
  api/src/main.ts
  backend/.eslintrc.js
  backend/.gitignore
  backend/.prettierrc
  backend/README.md
  backend/nest-cli.json
  backend/package-lock.json
  backend/package.json
  backend/src/app.controller.spec.ts
  backend/src/app.controller.ts
  backend/src/app.module.ts
  backend/src/app.service.ts
  backend/src/cats/cats.controller.spec.ts
  backend/src/cats/cats.controller.ts
  backend/src/main.ts
  backend/test/app.e2e-spec.ts
  backend/test/jest-e2e.json
  backend/tsconfig.build.json
  backend/tsconfig.json
Labels: api, hacktoberfest-accepted

#203 Fix error on datepicker antd upgrade
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/Components/form/AddNewEntryForm/AddNewEntryForm.tsx
  frontend/src/Components/menu/AppMenu/AppMenu.tsx
  frontend/src/Pages/Dashboard.tsx
  frontend/src/index.stories.tsx
Labels: hacktoberfest-accepted, ui

#204 Create docker setup for development purpose
  .docker/backend/Dockerfile
  .docker/frontend/Dockerfile
  .docker/traefik/traefik.dev.toml
  .dockerignore
  README.md
  backend/src/main.ts
  docker-compose.yaml
Labels: api, ui

#205 Add database with typeorm configs
  README.md
  backend/.env.example
  backend/.gitignore
  backend/.prettierrc
  backend/package-lock.json
  backend/package.json
  backend/src/app.module.ts
  backend/src/main.ts
  backend/src/models/base.entity.ts
  backend/src/transactions/entities/Transaction.entity.ts
  backend/src/transactions/transactions.controller.spec.ts
  backend/src/transactions/transactions.controller.ts
  backend/src/transactions/transactions.module.ts
  backend/src/transactions/transactions.service.spec.ts
  backend/src/transactions/transactions.service.ts
  backend/tsconfig.build.json
  docker-compose.yaml
Labels: api, hacktoberfest, hacktoberfest-accepted

#208 Implement JWT authentication
  backend/.env.example
  backend/package-lock.json
  backend/package.json
  backend/src/app.controller.ts
  backend/src/app.module.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/constants.ts
  backend/src/auth/jwt-auth.guard.ts
  backend/src/auth/jwt.strategy.ts
  backend/src/main.ts
Labels: api, hacktoberfest-accepted

#209 Add @nestjs/passport package for passport based authentication
  backend/.env.example
  backend/package-lock.json
  backend/package.json
  backend/src/app.controller.ts
  backend/src/app.module.ts
  backend/src/app.service.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.service.spec.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/constants.ts
  backend/src/auth/jwt-auth.guard.ts
  backend/src/auth/jwt.strategy.ts
  backend/src/auth/local-auth.guard.ts
  backend/src/auth/local.strategy.ts
  backend/src/main.ts
  backend/src/users/user.entity.ts
  backend/src/users/users.module.ts
  backend/src/users/users.service.ts
Labels: api, hacktoberfest-accepted

#207 add database integration and initiate user authentication
  backend/.env.example
  backend/package-lock.json
  backend/package.json
  backend/src/app.controller.ts
  backend/src/app.module.ts
  backend/src/app.service.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.service.spec.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/constants.ts
  backend/src/auth/jwt-auth.guard.ts
  backend/src/auth/jwt.strategy.ts
  backend/src/auth/local-auth.guard.ts
  backend/src/auth/local.strategy.ts
  backend/src/main.ts
  backend/src/roles.guard.ts
  backend/src/transactions/dto/transaction.dto.ts
  backend/src/transactions/entities/Transaction.entity.ts
  backend/src/transactions/transaction.entity.ts
  backend/src/transactions/transactions.controller.ts
  backend/src/transactions/transactions.module.ts
  backend/src/transactions/transactions.service.ts
  backend/src/users/dto/create-user.dto.ts
  backend/src/users/user.entity.ts
  backend/src/users/users.controller.spec.ts
  backend/src/users/users.controller.ts
  backend/src/users/users.module.ts
  backend/src/users/users.service.spec.ts
  backend/src/users/users.service.ts
Labels: api, hacktoberfest-accepted

#223 Update docker-compose
  .docker/backend/Dockerfile
  .docker/traefik/traefik.dev.toml
  backend/.env.example
  backend/src/app.controller.ts
  backend/src/main.ts
  docker-compose.yaml
Labels: api

#220 Remove cats controller
  backend/src/cats/cats.controller.spec.ts
  backend/src/cats/cats.controller.ts
Labels: hacktoberfest, hacktoberfest-accepted

#224 Fix npm build error
  frontend/config-overrides.js
  frontend/package-lock.json
  frontend/package.json
  frontend/tsconfig.json
Labels: bug
